#server:
#  error:
#    include-message: always
#    include-binding-errors: always


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    password: 12345678
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
debug: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html  #指定swagger-ui路徑
    enabled: true # 開啟swagger-ui
  api-docs:
    enabled: true
