# 作者: IanLiu
# 描述: 用於統一每個開發者的"開發環境"

version: '3.8'
services:
  db:
    container_name: 'postgresql'
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: puyuan
#    volumes:
#      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  dbGUI:
    container_name: 'pgadmin'
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5437:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'test@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'test'
      PGADMIN_SERVER_JSON_FILE: '/pgadmin4/pgadmin/server.json'
    volumes:
      - .\server.json:/pgadmin4/pgadmin/server.json
    depends_on:
      - db
    networks:
      - backend

  redis:
    container_name: 'myredis'
    image: redis:7.0-alpine
    restart: always
#    volumes:
#      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  db-data:
  redis-data:

networks:
  backend: